jdk:
- oraclejdk8

env:
  global:
  - secure: 2wDiQNXGZ6xqWbHSCRMrLY3Ip9iMZ2YfhPbjwhpIw4c29+k5NgOgaWBlP9cxj6jhknqChoovEnmIuQYg2H93SnfnMZlDlQNdI7NOORW4cyQNxZLPE/B4qjc/gN7nH9tpABsysecQ8Et0EX95ldxeOw9QJEp0PMsGi35QIkT2P8Sgfr6vQPRDQkZtkIPPQmIQqjUNdZ2VkZq2sh1eLH+C1yeo+a/Ul4MXPeuypLr76k+f1w92sNTKDzi0Rm8Yk2ihQVFLrxZhpPdjwzRZJZeWLAGHSGSogkJkNy105p86WpTco1eW1swkac4DMjJR5+Z0fKs187Y3Uf2hlhmuprTRhUM+O2/7+l6GjsLG/lC0FCRbwy9P2ApzK5qCvIVYG4WbuavwFU2MXsevykSQafm8vukH4aiNx9HiUqaimiO74+fmVeQLtYp+TRtZ7FGsGPU8tmNxlPEeqWSQAOzQZTc9CgZ/v+sxlqmTo8lOWuimXIRqzL1vYZyfxEoJK0PFZ7bg9lAZiR/ztl04Sz55lGs0gK+m/CBUXnK/WoYH9JQ9aTYUucOQm5zgl7iHyt0SIed0xxnh4y0PQccyNPiW7nUzrV21RNS8UPJ0C8tPLIObuO7CzWfi2oqeWAaSCeqMU1AlsjUFk2xE5yxGHMTzrKWd36pE6mD+XCEOXPq7LQ52qwk=
  - secure: "+pvy0FgOYaBl0+F8uzBx61WXwHpsixKBDZRzC1mKN85hjRT8iCIQSNwBpYRlAnC7sXsfxlJDWyyONsUNzA2LlFvL3qjsSg8ujeCBb+8C9UpNJa9Ti5wBamT8XxTgzPNBjEh5H0vOh5ZV7yI/rNRmAI437/cNI/CkF4AEHc77yBuyhVxnCybgNQgPNV+Feuq05PNyoVbakQRbPM4wycnbva+N5CvvmrQ6buJG8Xi2cO564TXpli9J9cTaTSzEvIIxJbSTcxpSa00gfOkFmZlq5AiNAk5uWRg5fV7zgdduAyTZ019dNkpctnF1voE5CZgb9FG3Cg0RLZ0qcWLx4bGBhYoVfzUoG56THlj+Sfe+DzWL/bmg5NvM1Ogk/FMFSrr0l/vcai1rpkrfK69uaNEOk0PCa2/E9iD/QDIqUUnzJuBR/eOoLumLRbvTzce1YI2Da4+hkn37wtZqehdAkG4YOqFss2x5Zt6o7ozXzl0dgcT8ZCPUlN8lnuyyXqP+9efIt0dRz5OdOkrsFOctMsl2lPwNtiTY1oc1/AbQ3yn/nm+0A9FAFMVVNGnpqh9tva46UpUoKmv8oy5knwrQYYp+NhzR8Xqu8WCnPVD4zh1kJfBGqMyvjPDw4rmPolX6SqWzw+wPk5q67QMsDShxQaGZ9iFLzRJUxvFnXU2ttNDT8rw="

script:
- mvn clean install -f pom.xml

after_success:
- chmod +x ./.travis/artifact-delete.sh
- chmod +x ./.travis/artifact-upload.sh
- "./.travis/artifact-delete.sh"
- "./.travis/artifact-upload.sh"
